"""add password field

Revision ID: 051b31a0f47b
Revises: e914fe8f0aa6
Create Date: 2023-03-27 16:08:10.661077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051b31a0f47b'
down_revision = 'e914fe8f0aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password'))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
