"""empty message

Revision ID: 4cd9ef091c8b
Revises: c71f6453f5dc
Create Date: 2023-04-13 13:45:19.960372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd9ef091c8b'
down_revision = 'c71f6453f5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followee_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('followers_followed_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_follows_followee_id', 'user', ['followee_id'], ['id'])
        batch_op.drop_column('followed_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_follows_followee_id', type_='foreignkey')
        batch_op.create_foreign_key('followers_followed_id_fkey', 'user', ['followed_id'], ['id'])
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('followee_id')

    # ### end Alembic commands ###
